FROM httpd:2.4
COPY ./public-html/ /usr/local/apache2/htdocs/
# Copy your conf file to /usr/local/apache2/conf/
# COPY ./your_apache_conf.conf /usr/local/apache2/conf/
# See https://hub.docker.com/_/httpd for more
